"use client";
import { useEffect, useMemo, useState } from "react";
import { createClient, type SupabaseClient } from "@supabase/supabase-js";

type Session = { id: string; account: string; status: string; task: string; next_step: string; files: string[]; updated_at: string };
type Event = { id: number; account: string; message: string; created_at: string };
const demoSessions: Session[] = [
  { id: "normal", account: "Claude normal", status: "working", task: "Aguardando conexão do projeto", next_step: "Conectar o repositório ShipFlow", files: [], updated_at: new Date().toISOString() },
  { id: "gateway", account: "Claude Gateway", status: "offline", task: "Nenhuma tarefa em andamento", next_step: "—", files: [], updated_at: new Date().toISOString() },
];
function getClient(): SupabaseClient | null { const url = process.env.NEXT_PUBLIC_SUPABASE_URL; const key = process.env.NEXT_PUBLIC_SUPABASE_PUBLISHABLE_KEY || process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY; return url && key ? createClient(url, key) : null; }

export default function Home() {
  const client = useMemo(getClient, []); const [sessions, setSessions] = useState<Session[]>(demoSessions); const [events, setEvents] = useState<Event[]>([{ id: 1, account: "Sistema", message: "Painel pronto para conectar o projeto ShipFlow.", created_at: new Date().toISOString() }]); const [task, setTask] = useState(""); const [account, setAccount] = useState("Claude normal"); const [notice, setNotice] = useState(client ? "Conectando ao painel online…" : "Modo demonstração — conecte o Supabase para usar online.");
  useEffect(() => { if (!client) return; const sb = client; let active = true; async function load() { const [{ data: sd }, { data: ed }] = await Promise.all([sb.from("agent_sessions").select("id,account,status,task,next_step,files,updated_at").order("updated_at", { ascending: false }), sb.from("activity_events").select("id,account,message,created_at").order("created_at", { ascending: false }).limit(30)]); if (!active) return; if (sd?.length) setSessions(sd as Session[]); if (ed?.length) setEvents(ed as Event[]); setNotice("Online e sincronizado"); } load(); const channel = sb.channel("claude-sync-live").on("postgres_changes", { event: "*", schema: "public", table: "agent_sessions" }, load).on("postgres_changes", { event: "INSERT", schema: "public", table: "activity_events" }, load).subscribe(); return () => { active = false; sb.removeChannel(channel); }; }, [client]);
  async function startWork() { const text = task.trim() || "Tarefa não informada"; const id = account === "Claude normal" ? "normal" : "gateway"; const updated: Session = { id, account, status: "working", task: text, next_step: "Atualizar o próximo passo no painel", files: [], updated_at: new Date().toISOString() }; setSessions((old) => [...old.filter((item) => item.id !== id), updated]); setEvents((old) => [{ id: Date.now(), account, message: `iniciou: ${text}`, created_at: new Date().toISOString() }, ...old]); setTask(""); if (client) { await client.from("agent_sessions").upsert(updated); await client.from("activity_events").insert({ account, message: `iniciou: ${text}` }); setNotice("Atividade sincronizada na internet"); } }
  async function finishWork() { const current = sessions.find((item) => item.account === account); if (!current) return; const updated = { ...current, status: "finished", next_step: "Aguardando nova tarefa", updated_at: new Date().toISOString() }; setSessions((old) => old.map((item) => item.id === current.id ? updated : item)); if (client) { await client.from("agent_sessions").upsert(updated); await client.from("activity_events").insert({ account, message: `finalizou: ${current.task}` }); } }
  const activeCount = sessions.filter((item) => item.status === "working").length;
  return <main className="shell"><header className="topbar"><div className="brand"><span className="brand-mark">↔</span><div><strong>Claude Sync</strong><span>painel online</span></div></div><div className="top-actions"><span className="connection"><i />{notice}</span><button className="ghost">Entrar com GitHub</button></div></header><div className="content"><section className="welcome"><div><p className="eyebrow">PROJETO CONECTADO</p><h1>ShipFlow</h1><p className="sub">Acompanhe as duas contas sem procurar arquivos ou abrir o histórico.</p></div><div className="pulse"><b>{activeCount}</b><span>conta{activeCount === 1 ? "" : "s"} trabalhando agora</span></div></section><section className="cards">{sessions.map((item) => <article className="agent-card" key={item.id}><div className="card-head"><div className="avatar">{item.id === "normal" ? "N" : "G"}</div><div><h2>{item.account}</h2><span className={`status ${item.status}`}><i />{item.status === "working" ? "Trabalhando agora" : item.status === "finished" ? "Finalizou" : "Aguardando"}</span></div><span className="time">{new Date(item.updated_at).toLocaleTimeString("pt-BR", { hour: "2-digit", minute: "2-digit" })}</span></div><div className="task-box"><span>TAREFA ATUAL</span><strong>{item.task}</strong></div><div className="next"><span>Próximo passo</span><b>{item.next_step}</b></div>{item.files.length > 0 && <div className="files">{item.files.slice(0, 3).map((file) => <code key={file}>{file}</code>)}</div>}</article>)}</section><section className="workspace"><div className="section-title"><div><p className="eyebrow">CONTROLE RÁPIDO</p><h2>Atualizar atividade</h2></div><span className="cloud-badge">● salvo na nuvem</span></div><div className="form-grid"><label>Qual conta está trabalhando<select value={account} onChange={(e) => setAccount(e.target.value)}><option>Claude normal</option><option>Claude Gateway</option></select></label><label className="wide">O que está sendo feito<input value={task} onChange={(e) => setTask(e.target.value)} placeholder="Ex.: corrigindo integração com pedidos" /></label></div><div className="buttons"><button className="primary" onClick={startWork}>Iniciar / atualizar tarefa</button><button className="secondary" onClick={finishWork}>Finalizar tarefa</button></div></section><section className="activity"><div className="section-title"><div><p className="eyebrow">HISTÓRICO AO VIVO</p><h2>Últimas atividades</h2></div><span className="live"><i /> atualização em tempo real</span></div>{events.slice(0, 8).map((event) => <div className="event" key={event.id}><span className="event-dot" /><div><b>{event.account}</b><span>{event.message}</span></div><time>{new Date(event.created_at).toLocaleTimeString("pt-BR", { hour: "2-digit", minute: "2-digit" })}</time></div>)}</section></div></main>;
}
